CREATE TABLE bh_details(
   "Boarding house name"  VARCHAR(32) NOT NULL PRIMARY KEY
  ,"Boarding house owner" VARCHAR(31)
  ,Location               VARCHAR(76)
  ,Amenities              VARCHAR(57)
  ,Rate                   VARCHAR(32)
  ,Vacancy                VARCHAR(118)
  ,"Contact Number"       INTEGER 
  ,FIELD8                 VARCHAR(30)
);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('RRE BOARDING HOUSE','Victor Casas','Padre Inocentes Garcia Naval Biliran','free water & no free electricity & 10:00 pm- curfew','1400 monthly','9 rooms (4 Ang nag occupy each room)',9354425488,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('BEBIANS BOARDING HOUSE','Bebian Bornillo Dangel','Castin St.,  Santissimo Rosario Pob. Naval Biliran','no free water & electricity & No curfew','3500 monthly','3 rooms( each room 6 ang nag occupy)',9483726354,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JOSEPHINE BOARDING HOUSE','Josephine Mangco Adobo','Castin St.,  Santissimo Rosario Pob. Naval Biliran','no free water& electricity & swimming pool & No Curfew','3500 monthly & 40 per head','2 rooms (each room 6 Ang nag occupy)',9120814592,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ALIYAH''S BOARDING HOUSE','Ma. Florlyn Olaivar Docallos','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','10:00pm- curfew','1200 monthly','8 rooms (4 ka rooms- 4 Ang nag occupy each room )',9173240900,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('TRIPLE-L BOARDING HOUSE','Lorna Logro Leoveras','Castin St.,  Santissimo Rosario Pob. Naval Biliran','for  family room/Aircon & Swimming pool & 10:pm- curfew','1500 & 3k Monthly & 40 per head','6 rooms (each room 6 Ang nag occupy) & 9 rooms for family',9978532615,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('CYCLECARE BOARDING HOUSE','Junrey Arevalo Salut','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','free water & electricity & 10 pm curfew','1000 monthly','3 rooms (dipindi sa room nga nag occupy, may 8, 7, 3)',9631191992,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('RUIZ GAVIOLA BOARDING HOUSE','Emmylou Gaviola De Leon','Sagrada Familia Homes, Caneja Ext.,  Padre Inocentes Garcia Naval Biliran','free electricity & no free water & free water/electricity','1000 & 1300','3 rooms  available',9357168544,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('NORBE TESS BOARDING HOUSE','Norbe Martinito Bangcuyo','Sitio Butay.,  Padre Inocentes Garcia Naval Biliran','free  electricity  and no curfew','1250 monthly','10 rooms/ 4 rooms available',9473014529,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('F.V. MADEJA''S BOARDING HOUSE','Elna Bornillo Madeja','Across BIPSU,  P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','free water and electricity','1200 monthly','9 rooms available',9032566584,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('F S BOARDING HOUSE','Sonia Sermo Alavera','Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','no free electricity','1000 monthly','6 rooms available',9753333435,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('GBOY''S BOARDING HOUSE','Gilbert Masibag Padar','Sitio Butay,  Padre Inocentes Garcia Naval Biliran','no curfew and free water','1100 monthly','10 rooms available',9084188245,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('PADAR''S BOARDING HOUSE','Rosila Masibag Padar','Caneja St.,  Padre Inocentes Garcia Naval Biliran','free all','1200 monthly','1 rooms (4 occupied person)',9293712834,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ATCCA''S BOARDING HOUSE','Arnel Santos','Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','free water & electricity & 10 pm curfew','1000 monthly','26 rooms (naka dipindi sa room naay tag 8 ug 6 ka mga bed spacer each room)
Damo han bakante na mga room',9302399157,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('CHRISLYD BOARDING HOUSE','Krizyl Mae Castin Meniel','Vicentillo St.  Padre Inocentes Garcia Naval Biliran','free water& electricity)
Free wifi & No Curfew','1200 monthly','8 rooms (4 rooms- max. of 6 person nga pwede mag occupy
               (4 rooms- max. of 8 person nga pwede mag occupy',9171353572,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('BELEN G. AREVALO BOARDING HOUSE','Belen Gaturian Arevalo','Vicentillo Ext. St.,  Padre Inocentes Garcia Naval Biliran','No curfew','1300 monthly per head','4 rooms (each room max. of 4 person nga pwede mag occupy)',9048564732,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('TEA-MAYET BOARDING HOUSE','Marietta Cotejar Ebio','Sitio Santol,   Padre Inocentes Garcia Naval Biliran','no free water& electricity & 10:00pm curfew','1000 monthly','8 rooms( each room max. 3 person Ang pwede mag occupy)',9658105511,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JAS'' BOARDING HOUSE','JASMIN PERDUGAS SALUT','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','No curfew','1200 monthly','6 rooms(4 person can occupy each room)',9362738254,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('PSC BOARDING HOUSE','PABLITO SOLITE CUIZON','sITIO BUTAY  Padre Inocentes Garcia Naval Biliran','10pm curfew','1000 per head','4 rooms (each room max. of 6  person can occupy)',9129992645,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('CCC BEDS N'' SPACE RENTAL','CARLITO CURSO CABAS JR.','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','free all','1300 monthly','9 rooms available',9558448898,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('MB BOARDING HOUSE','MICHELLE DACASIN BAYLON','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','no free water & electricity & No curfew','1200 monthly','6  bed spacer vacant',9411659653,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('TEA-MAYET BOARDING HOUSE','MARIETTA COTEJAR EBIO','Sitio Santol,   Padre Inocentes Garcia Naval Biliran','no free wifi, no free water and electricity','950 monthly per head','4 rooms availabe',9657348261,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('R AND L BOARDING HOUSE','LOURDES OLIVA LIMPIADO','Vicentillo Ext.,   Padre Inocentes Garcia Naval Biliran','fee all','1300 monthly','7 bed spacer vacant',9584621123,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JAIME P. GOMEZ BOARDING HOUSE','JAIME PICA GOMEZ','Bernardes Village, Atipolo Naval Biliran','10pm curfew,free wifi, free all','1500 monthly','8 rooms(each room 4 person can occupy)',9738473849,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('PADAR''S BOARDING HOUSE','ROSILA MASIBAG PADAR','Caneja St.,  Padre Inocentes Garcia Naval Biliran','free all','1300 monthly','4 rooms (each room 6 person can occupy)',9036275192,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('FRANCINEMATTHIEW BOARDING HOUSE','FRANCISCO ROSAROSO BAYLON','Sitio Tacung,  Padre Inocentes Garcia Naval Biliran','free all','1500 montly','5 bed spacer vacant',9874587478,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ROSARIO P. NAPARI DORMITORY','ROSARIO DELA PENA NAPARI','476   Vicentillo St.  Padre Inocentes Garcia Naval Biliran','free ricecooker,free water and electricity,10pm curfew','1400 monthly per head','3 rooms (each room2 person can occupy)',9340726384,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JEPRY A. BOARDING HOUSE','JEPRY BAYLON ABREA','P. INOCENTES STREET  Padre Inocentes Garcia Naval Biliran','free wifi,and water,9pm curfew','1000 monthly','1 room (4 occupied person)',9372839405,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ATCCA''S BOARDING HOUSE','ARNEL  SANTOS','Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','free water and electricity','1200 monthly','2 rooms ( 6 person can occupy',9273840274,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('NEL-DO BOARDING HOUSE','TEODORA QUIJANO SANTOS','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','free wifi ,10pm curfew','1000 monthly','4 rooms (8 person can occupy)',9127302834,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('RLJ BOARDING HOUSE','RICARDO SABONG JORGE','Vicentillo Ext. St.,  Padre Inocentes Garcia Naval Biliran','no free','900 monthly','9 rooms available (each room 4 person can occupy)',9120914593,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('BELEN G. AREVALO BOARDING HOUSE','BELEN GATURIAN AREVALO','Vicentillo Ext. St.,  Padre Inocentes Garcia Naval Biliran','free wifi and ricecooker','1000 monthly','10 rooms (2 person can occupy)',9270347892,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('STEPHEN BOARDING HOUSE','STEPHEN UY BETONIO','Calumpang Naval Biliran','free all,','1300 monthly','6 rooms (each room 4 person can occupy)',9273849092,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('RM DORMITORY','ROMER MANGCO MAGPATOC','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','no free wifi, free water and electricity','1200 monthly','3 rooms  (each room 4 person can occupy)',9270914592,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('MARGIE BOARDING HOUSE','MARGARITA OLIVA BOTASTAS','Padre Inocentes Garcia Naval Biliran','free all ,airconditioned ,with mini ref','1500 monthly','4 rooms(each room 2 person can occupy)',9050527182,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ALIYAH''S BOARDING HOUSE','MA. FLORLYN OLAIVAR DOCALLOS','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','no curfew','900 monthy','4 rooms (6 person can occupy)',9050172839,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('GBOY''S BOARDING HOUSE','GILBERT MASIBAG PADAR','Sitio Butay,  Padre Inocentes Garcia Naval Biliran','free wifi,no curfew','1000 monthly','6 rooms ( 4 person can occupy)',9270362783,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('PANGAN BOARDING HOUSE','RACHEL JIMENO PANGAN','Sitio Butay,  Padre Inocentes Garcia Naval Biliran','free water and electricity','1200 monthly','2 rooms (4 person can occupy)',9053847263,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JOHN LOU AND KING BOARDING HOUSE','TERESITA MEJARES SABORDO','Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','no curfew, with ref each room','1000 monthly','5 rooms (each room 4 person can occupy)',9270162783,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('MACOI 1 BOARDING HOUSE','MARK GERALD EVANGELISTA DACER','526   Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','10pm curfew ,airconditioned','1200 monthly per head','2 rooms (2 person caan occupy)',9058372654,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('MACOI1 BOARDING HOUSE','MARK GERALD  EVANGELISTA DACER','502,   Vicentillo St.,  Padre Inocentes Garcia Naval Biliran','9pm curfew ,free wifi','1100 monthly per head','4 rooms (each room 2 person can occupy)',9203748957,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('J.C.F. BOARDING HOUSE','ANGELITO LIPOMANO ALKUINO','P. Inocentes St.,  Padre Inocentes Garcia Naval Biliran','free water,wifi and electricity','1300 monthly','1 room (4 person can occupy)',9302837465,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('VILMA BOARDING HOUSE','VILMA CAMANSE MAMAC','Padre Inocentes Garcia Naval Biliran','no free','1100 monthly','4 rooms availabe',9072738493,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('DAVID BOARDING HOUSE','CLARA GERMAN DAVID','Padre Inocentes Garcia Naval Biliran','free all','1200 monthly','4 rooms  (2 person can occupy)',9270372651,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('NYT ROCHAT BOARDING HOUSE','NERLYN CONGE ROCHAT','Calumpang Naval Biliran','free wifi, 10pm curfew','1000 monthly','3 rooms (4 person can occupy)',9528376152,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('EBRON''S BOARDING HOUSE','SEQUELA CHING EBRON','Padre Inocentes Garcia Naval Biliran','free water and electricity','1100 monthly','3 rooms (2 person can occupy)',9267350263,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('CHONA''S BOARDING HOUSE','CHONA BRENGA BOS','Vicentillo St  Padre Inocentes Garcia Naval Biliran','no free water,wifi,and electricity','950 monthly per head','1 room (4 occupied person)',9262914572,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ROGER TEJAM BOARDING HOUSE','EMILIA IMPAS PALLO','sitio tacung  Padre Inocentes Garcia Naval Biliran','free wifi,water ,electricity and ricecooker per room','1300 monthly','2 rooms (each room 6 person can occupy)',9037465748,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ROBERTO BOARDING HOUSE','ROBERTO LENTIAS SERRATO','VICENTILLO  Padre Inocentes Garcia Naval Biliran','free all','1300 monthly','5 rooms (each room 4 person can occupy)',9267384936,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('ANGELO''S BOARDING HOUSE','ANGELO LANTAJO','Padre Inocentes Garcia Naval Biliran','free water and electricity','850 monthly','4 rooms (2 person can occupy)',9260914573,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JFA BOARDING HOUSE','JERICHO VLLARDAR','Padre Inocentes Garcia Naval Biliran','free water,wifi and electricity','1100 monthly','4 rooms  available',9035273820,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('KENNETH BOARDING HOUSE','KENNETH ROSTATA','Calumpang Naval Biliran','free wifi','1000 monthly','4 rooms (2 person can occupy)',9026372819,NULL);
INSERT INTO bh_details("Boarding house name","Boarding house owner",Location,Amenities,Rate,Vacancy,"Contact Number",FIELD8) VALUES ('JONA BOARDING HOUSE','JONA MOCORRO','Padre Inocentes Garcia Naval Biliran','no free ,11pm curfew','1100 monthly','2 rooms available',9126537255,NULL);